spring:
  application:
    name: myspringboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootproduct?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    # mybatis扫描别名包，和注解@Alias联用
    type-aliases-package: myspringboot.pojo

  redis:
    host: 127.0.01
    port: 6379
    password: 123
    expirationTime: 3600

    jedis:
      pool:
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        max-idle: 10
        min-idle: 0
        timeout: 1000
        ex: 3600
        #限制单个文件夹大小最大为5MB
        max-file-size: 5242800

    database: 0
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    publisher-confirm-type: correlated

  thymeleaf:
    prefix: classpath:/templates/jsp/
    suffix: .jsp

server:
  port: 8080



